version: '1.0'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.19.4
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    hostname: elasticsearch
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200 > /dev/null || exit 1"]
      start_period: 10s
      interval: 30s
      timeout: 10s
      retries: 10
    networks:
      - tmf-network
    mem_limit: 1g

  kafkaServer:
    image: apache/kafka:3.9.1
    hostname: kafkaServer
    ports:
      - "9092:9092"
    
    container_name: kafka
    environment:
      KAFKA_KRAFT_MODE: 'true'
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_LISTENERS: PLAINTEXT://kafkaServer:9092,CONTROLLER://kafkaServer:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafkaServer:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafkaServer:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    healthcheck:
      test: ["CMD-SHELL", "/opt/kafka/bin/kafka-broker-api-versions.sh --bootstrap-server kafkaServer:9092 || exit 1"]
      start_period: 10s
      interval: 15s
      timeout: 10s
      retries: 10
    networks:
      - tmf-network
    depends_on:
      elasticsearch:
        condition: service_healthy
  
  kafka-init:
    image: apache/kafka:3.9.1
    container_name: kafka-init
    depends_on:
      kafkaServer:
        condition: service_healthy

    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      "
      /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafkaServer:9092 --list

      echo -e 'Creating kafka topics'
      /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafkaServer:9092 --create --if-not-exists --topic new_point --replication-factor 1 --partitions 1
      /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafkaServer:9092 --create --if-not-exists --topic data_enriched --replication-factor 1 --partitions 1
      /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafkaServer:9092 --create --if-not-exists --topic connect-configs --replication-factor 1 --partitions 1 --config cleanup.policy=compact
      /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafkaServer:9092 --create --if-not-exists --topic connect-offsets --replication-factor 1 --partitions 1 --config cleanup.policy=compact
      /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafkaServer:9092 --create --if-not-exists --topic connect-status --replication-factor 1 --partitions 1 --config cleanup.policy=compact

      echo -e 'Successfully created the following topics:'
      /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafkaServer:9092 --list
      "
    networks:
      - tmf-network
  kafka-producer:
    build:
      context: ingestion
      dockerfile: Dockerfile
    container_name: kafka-producer
    depends_on:
      kafkaServer: 
        condition: service_healthy
      kafka-init:
        condition: service_completed_successfully
    environment:
      PYTHONUNBUFFERED: 1
    networks:
      - tmf-network
  
  kafka-connect:
    image: confluentinc/cp-kafka-connect:7.7.5
    container_name: kafka-connect
    depends_on:
      kafkaServer:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
      kafka-init:
        condition: service_completed_successfully
    ports:
      - "8083:8083"
    mem_limit: 1g
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://kafka-connect:8083/connectors || exit 1"]
      start_period: 10s
      interval: 15s
      timeout: 10s
      retries: 10
    environment:
      CONNECT_BOOTSTRAP_SERVERS: 'kafkaServer:9092'
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: 'connect-cluster'
      CONNECT_CONFIG_STORAGE_TOPIC: 'connect-configs'
      CONNECT_OFFSET_STORAGE_TOPIC: 'connect-offsets'
      CONNECT_STATUS_STORAGE_TOPIC: 'connect-status'
      CONNECT_OFFSET_STORAGE_TOPIC_REPLICATION_FACTOR: 1
      CONNECT_CONFIG_STORAGE_TOPIC_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_TOPIC_REPLICATION_FACTOR: 1
      CONNECT_KEY_CONVERTER: 'org.apache.kafka.connect.json.JsonConverter'
      CONNECT_VALUE_CONVERTER: 'org.apache.kafka.connect.json.JsonConverter'
      CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE: 'false'
      CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE: 'false'
      CONNECT_REST_ADVERTISED_HOST_NAME: 'kafka-connect'
      CONNECT_PLUGIN_PATH: '/usr/share/java,/usr/share/confluent-hub-components/'
      KAFKA_HEAP_OPTS: "-Xms512M -Xmx512M"
    volumes:
      - ./streaming/connect-plugins:/usr/share/confluent-hub-components
    networks:
      - tmf-network
  kafka-connect-init:
    image: alpine/curl:8.14.1
    container_name: kafka-connect-init
    depends_on:
      kafka-connect:
        condition: service_healthy
    command: ["sh", "run.sh"]

    volumes:
      - ./streaming/run.sh:/run.sh
      - ./streaming/connectors:/connectors
    networks:
      - tmf-network
volumes:
  esdata: 

networks:
  tmf-network: